In [1]:
import pandas as pd

import sys

sys.path.append("../src")

from indicators import create_indicators

In [2]:
forex = pd.read_csv("../data/forex_price_data.csv")

In [3]:
forex = create_indicators(forex)

In [4]:
forex.head()

,DateTime,PairID,PairName,Open,High,Low,Close,Volume,Spread,Return,SMA20,SMA50,EMA20,EMA50,RSI,MACD,MACDSignal,BBUpper,BBLower
0,2023-01-01 00:00:00,1,EUR/USD,1.08103,1.08103,1.08019,1.08054,2651,0.9,NaN,NaN,NaN,1.080540,1.080540,NaN,NaN,NaN,NaN,NaN
1,2023-01-01 01:00:00,1,EUR/USD,1.08010,1.08043,1.07974,1.08028,2292,1.0,-0.000241,NaN,NaN,1.080404,1.080407,NaN,NaN,NaN,NaN,NaN
2,2023-01-01 02:00:00,1,EUR/USD,1.08036,1.08158,1.07961,1.08054,1796,1.2,0.000241,NaN,NaN,1.080454,1.080453,NaN,NaN,NaN,NaN,NaN
3,2023-01-01 03:00:00,1,EUR/USD,1.08068,1.08126,1.07973,1.08088,4019,1.4,0.000315,NaN,NaN,1.080577,1.080567,NaN,NaN,NaN,NaN,NaN
4,2023-01-01 04:00:00,1,EUR/USD,1.08042,1.08042,1.07967,1.08030,2207,1.6,-0.000537,NaN,NaN,1.080510,1.080509,NaN,NaN,NaN,NaN,NaN

In [5]:
forex[
[
"Close",
"SMA20",
"SMA50",
"RSI",
"MACD"
]
].tail()

       Close     SMA20     SMA50        RSI      MACD
495  1.10861  1.113773  1.113324  28.186279 -0.001262
496  1.10739  1.113284  1.113290  25.076850 -0.001505
497  1.10713  1.112755  1.113260  24.457616 -0.001700
498  1.10758  1.112228  1.113245  27.781563 -0.001796
499  1.10895  1.111777  1.113236  36.886526 -0.001742

In [6]:
forex.to_csv(
    "../data/processed_forex.csv",
    index=False
)